version: '3.8'

services:
  app:
    build: .
    container_name: api_ecommerce_app
    ports:
      - "8080:8080"
    environment:
      SPRING_PROFILES_ACTIVE: h2
    volumes:
      - h2_data:/data/h2

volumes:
  h2_data: