spring.datasource.url=jdbc:postgresql://localhost:5432/ecommerce
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.username=postgres
<<<<<<< HEAD
spring.datasource.password=72021

spring.profiles.active=pg
=======
spring.datasource.password=root
>>>>>>> add26c7d9d9a1e5f2b5352773205597d81897c18

spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

springdoc.api-docs.enabled=false
springdoc.swagger-ui.enabled=false
